### ISSUE TITLE
Craigslist Scraper not pulling anything with valid search criteria.

### ISSUE THREAD

**Issue by TechWithTy** [ryanirl/CraigslistScraper#4]
from craigslistscraper import Searches

if __name__ == '__main__': # Required to run inside of "if name == main"

  filters = ['&postedToday=1'] # Optional | Define your filters here

  cities = ['Denver','Miami'] # Required | Define the cities you want to search

  # car_data=False by default and doesn't need to be defined explicitly.
  foo = Searches("Moving", cities, car_data=False)
  
  foo.compile_search()

yields an empty json

**Comment by ryanirl** [comment]
It's been awhile since I worked on this project, but it seems they recently upgraded their site. If that is the case, then this repo will need some work before it works again. I tried running it with scripts that had previously worked for me and their failing also. I don't have the bandwidth to work on it this month, but feel free to fork it and see if you can make it compatible with the new updates.
